### ISSUE TITLE
code error 

### ISSUE THREAD

**Issue by Gteck55** [nikkkhil067/Sign-Language-To-Text-Conversion#11]
python3 Application.py
2024-02-08 12:18:41.101119: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-02-08 12:18:41.130207: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-08 12:18:41.130235: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-08 12:18:41.131109: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-08 12:18:41.135484: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-02-08 12:18:41.135640: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-08 12:18:41.717909: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Starting Application...
Error initializing HunSpell: <class 'HunSpell'> returned a result with an exception set
2024-02-08 12:18:42.081677: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:274] failed call to cuInit: CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE: forward compatibility was attempted on non supported HW
2024-02-08 12:18:42.081721: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:129] retrieving CUDA diagnostic information for host: gaurav-IdeaPad-Gaming-3-15IMH05
2024-02-08 12:18:42.081727: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:136] hostname: gaurav-IdeaPad-Gaming-3-15IMH05
2024-02-08 12:18:42.081782: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:159] libcuda reported version is: 535.86.5
2024-02-08 12:18:42.081816: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:163] kernel reported version is: 535.54.3
2024-02-08 12:18:42.081821: E external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:244] kernel version 535.54.3 does not match DSO version 535.86.5 -- cannot find working devices in this configuration
Loaded model from disk
1/1 [==============================] - 0s 75ms/step
1/1 [==============================] - 0s 99ms/step
1/1 [==============================] - 0s 51ms/step
1/1 [==============================] - 0s 51ms/step
Error: 'hs' attribute not initialized.
Traceback (most recent call last):
  File "/home/gaurav/Desktop/Sign-Language-To-Text-Conversion-main/Application.py", line 398, in <module>
    (Application()).root.mainloop()
  File "/home/gaurav/Desktop/Sign-Language-To-Text-Conversion-main/Application.py", line 126, in __init__
    self.video_loop()
  File "/home/gaurav/Desktop/Sign-Language-To-Text-Conversion-main/Application.py", line 185, in video_loop
    if(len(predicts) > 1):
UnboundLocalError: local variable 'predicts' referenced before assignment

**Comment by emnikhil** [comment]
Check on all the required Libraries required to be installed before running, as in the error log CUDA is missing and many other libraries are also missing.
So, check it on the README file, I have listed all the required libraries to run this project.

**Comment by Gteck55** [comment]
thankyou for your help its reuuning propelry can you let me know that can i run this code on raspberry pi as a part of my project i need to run it on pi

**Comment by Gteck55** [comment]
and one more thing i want to know can i modify the dataset of code to isl indian sign language using your code will it be able to create model files ?

**Comment by emnikhil** [comment]
I don't have any experience and information if you can run it on raspberry pi.
you can try and figure it out.
For your second question, yes you can modify the dataset.
The file for creating dataset is TrainingDataCollection.py and TestDataCollection.py, you need to make changes based on the Indian sign language for it, and you need to re train the model agian, but for that I think you need to make changes in the model training files also, which are present in the Models folder.

**Comment by Gteck55** [comment]
Thankyou so much it will help me a lot
